
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.yeferal.desktopreproductor.gramm.list;

/** CUP generated class containing symbol constants. */
public class SymbolListCode {
  /* terminals */
  public static final int dos_puntos = 12;
  public static final int coma = 11;
  public static final int llave_c = 8;
  public static final int random = 4;
  public static final int llave_a = 7;
  public static final int cadena = 15;
  public static final int corchete_c = 10;
  public static final int EOF = 0;
  public static final int corchete_a = 9;
  public static final int lista = 2;
  public static final int pistas = 6;
  public static final int error = 1;
  public static final int false_rsv = 14;
  public static final int circular = 5;
  public static final int true_rsv = 13;
  public static final int nombre = 3;
  public static final int identificador = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "lista",
  "nombre",
  "random",
  "circular",
  "pistas",
  "llave_a",
  "llave_c",
  "corchete_a",
  "corchete_c",
  "coma",
  "dos_puntos",
  "true_rsv",
  "false_rsv",
  "cadena",
  "identificador"
  };
}

