
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.reproductor.gramm.comunication;

/** CUP generated class containing symbol constants. */
public class SymbolComCode {
  /* terminals */
  public static final int frecuencia = 27;
  public static final int pistas_c = 22;
  public static final int pistas_a = 21;
  public static final int cerrar = 38;
  public static final int igual = 39;
  public static final int tipo_c = 7;
  public static final int tipo_a = 6;
  public static final int identificador = 41;
  public static final int do_rsv = 44;
  public static final int pista = 5;
  public static final int aleatorio = 18;
  public static final int sol = 48;
  public static final int mi = 46;
  public static final int pista_c = 28;
  public static final int lista_c = 13;
  public static final int lista = 4;
  public static final int si = 55;
  public static final int lista_a = 12;
  public static final int sol_s = 53;
  public static final int nombre_c = 9;
  public static final int nombre_a = 8;
  public static final int octava_c = 35;
  public static final int fa_s = 52;
  public static final int numero = 42;
  public static final int octava_a = 34;
  public static final int canal_c = 25;
  public static final int EOF = 0;
  public static final int canal_a = 31;
  public static final int duracion = 17;
  public static final int nombre = 14;
  public static final int error = 1;
  public static final int solicitud_c = 3;
  public static final int solicitud_a = 2;
  public static final int si_rsv = 19;
  public static final int fa = 47;
  public static final int la = 49;
  public static final int re = 45;
  public static final int nota_c = 33;
  public static final int pista_ab = 16;
  public static final int nota_a = 32;
  public static final int datos_c = 30;
  public static final int listas_c = 11;
  public static final int datos_a = 29;
  public static final int listas_a = 10;
  public static final int canal_ab = 23;
  public static final int la_s = 54;
  public static final int re_s = 51;
  public static final int duracion_c = 37;
  public static final int nota_ab = 26;
  public static final int no = 20;
  public static final int duracion_a = 36;
  public static final int decimal = 43;
  public static final int numero_rsv = 24;
  public static final int pistas = 15;
  public static final int do_s = 50;
  public static final int cadena = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "solicitud_a",
  "solicitud_c",
  "lista",
  "pista",
  "tipo_a",
  "tipo_c",
  "nombre_a",
  "nombre_c",
  "listas_a",
  "listas_c",
  "lista_a",
  "lista_c",
  "nombre",
  "pistas",
  "pista_ab",
  "duracion",
  "aleatorio",
  "si_rsv",
  "no",
  "pistas_a",
  "pistas_c",
  "canal_ab",
  "numero_rsv",
  "canal_c",
  "nota_ab",
  "frecuencia",
  "pista_c",
  "datos_a",
  "datos_c",
  "canal_a",
  "nota_a",
  "nota_c",
  "octava_a",
  "octava_c",
  "duracion_a",
  "duracion_c",
  "cerrar",
  "igual",
  "cadena",
  "identificador",
  "numero",
  "decimal",
  "do_rsv",
  "re",
  "mi",
  "fa",
  "sol",
  "la",
  "do_s",
  "re_s",
  "fa_s",
  "sol_s",
  "la_s",
  "si"
  };
}

