
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.yeferal.desktopreproductor.gramm.main;

/** CUP generated class containing symbol constants. */
public class SymbolMainCode {
  /* terminals */
  public static final int caracter_special_hashtag = 44;
  public static final int corchete_c = 53;
  public static final int menos = 29;
  public static final int corchete_a = 52;
  public static final int identificador = 5;
  public static final int do_s = 89;
  public static final int caracter_rsv = 13;
  public static final int impares = 77;
  public static final int descendente = 75;
  public static final int mayor_q = 17;
  public static final int menos_menos = 50;
  public static final int div = 31;
  public static final int menor_igual = 20;
  public static final int llave_c = 55;
  public static final int mas = 28;
  public static final int cadena = 37;
  public static final int llave_a = 54;
  public static final int mientras = 66;
  public static final int mayor_igual = 19;
  public static final int sino = 57;
  public static final int false_rsv = 40;
  public static final int sumarizar = 79;
  public static final int reproducir = 71;
  public static final int do_rsv = 83;
  public static final int decimal = 41;
  public static final int arreglo = 51;
  public static final int caso = 62;
  public static final int caracter_special_t = 46;
  public static final int caracter_special_r = 45;
  public static final int caracter_special_n = 47;
  public static final int principal = 82;
  public static final int void_rsv = 70;
  public static final int or = 24;
  public static final int switch_rsv = 61;
  public static final int caracter = 38;
  public static final int extiende = 6;
  public static final int nand = 23;
  public static final int is_null = 21;
  public static final int esperar = 72;
  public static final int comentario_bloque = 3;
  public static final int comentario_linea = 2;
  public static final int igual_igual = 15;
  public static final int caracter_special_comilla_simple = 43;
  public static final int ascendente = 74;
  public static final int and = 22;
  public static final int retornar = 69;
  public static final int fa_s = 91;
  public static final int xor = 26;
  public static final int mas_igual = 48;
  public static final int EOF = 0;
  public static final int keep = 34;
  public static final int dos_puntos = 9;
  public static final int true_rsv = 39;
  public static final int pista = 4;
  public static final int primos = 78;
  public static final int numero = 42;
  public static final int mas_mas = 49;
  public static final int potencia = 33;
  public static final int default_rsv = 64;
  public static final int error = 1;
  public static final int la_s = 93;
  public static final int mi = 85;
  public static final int continuar = 68;
  public static final int boolean_rsv = 12;
  public static final int diferente = 16;
  public static final int si = 56;
  public static final int re_s = 90;
  public static final int mensaje = 81;
  public static final int entero = 10;
  public static final int sol = 87;
  public static final int sol_s = 92;
  public static final int salir = 63;
  public static final int hacer = 67;
  public static final int pares = 76;
  public static final int por = 30;
  public static final int para = 65;
  public static final int longitud = 80;
  public static final int menor_q = 18;
  public static final int sino_si = 58;
  public static final int coma = 7;
  public static final int modulo = 32;
  public static final int not = 27;
  public static final int doble = 11;
  public static final int igual = 36;
  public static final int nor = 25;
  public static final int fa = 86;
  public static final int pa_c = 60;
  public static final int var = 35;
  public static final int pa_a = 59;
  public static final int la = 88;
  public static final int ordenar = 73;
  public static final int punto_coma = 8;
  public static final int re = 84;
  public static final int cadena_rsv = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "comentario_linea",
  "comentario_bloque",
  "pista",
  "identificador",
  "extiende",
  "coma",
  "punto_coma",
  "dos_puntos",
  "entero",
  "doble",
  "boolean_rsv",
  "caracter_rsv",
  "cadena_rsv",
  "igual_igual",
  "diferente",
  "mayor_q",
  "menor_q",
  "mayor_igual",
  "menor_igual",
  "is_null",
  "and",
  "nand",
  "or",
  "nor",
  "xor",
  "not",
  "mas",
  "menos",
  "por",
  "div",
  "modulo",
  "potencia",
  "keep",
  "var",
  "igual",
  "cadena",
  "caracter",
  "true_rsv",
  "false_rsv",
  "decimal",
  "numero",
  "caracter_special_comilla_simple",
  "caracter_special_hashtag",
  "caracter_special_r",
  "caracter_special_t",
  "caracter_special_n",
  "mas_igual",
  "mas_mas",
  "menos_menos",
  "arreglo",
  "corchete_a",
  "corchete_c",
  "llave_a",
  "llave_c",
  "si",
  "sino",
  "sino_si",
  "pa_a",
  "pa_c",
  "switch_rsv",
  "caso",
  "salir",
  "default_rsv",
  "para",
  "mientras",
  "hacer",
  "continuar",
  "retornar",
  "void_rsv",
  "reproducir",
  "esperar",
  "ordenar",
  "ascendente",
  "descendente",
  "pares",
  "impares",
  "primos",
  "sumarizar",
  "longitud",
  "mensaje",
  "principal",
  "do_rsv",
  "re",
  "mi",
  "fa",
  "sol",
  "la",
  "do_s",
  "re_s",
  "fa_s",
  "sol_s",
  "la_s"
  };
}

